qwen1.5-1.8b: /mnt/petrelfs/jiangshuyang/checkpoints/Qwen1.5-1.8B-Chat
qwen1.5-7b: /mnt/petrelfs/jiangshuyang/checkpoints/Qwen1.5-7B-Chat
qwen1.5-14b: /mnt/petrelfs/jiangshuyang/checkpoints/Qwen1.5-14B-Chat
qwen1.5-32b: /mnt/petrelfs/jiangshuyang/checkpoints/Qwen1.5-32B-Chat
qwen2-7b: /mnt/petrelfs/jiangshuyang/checkpoints/Qwen2-7B-Instruct-lys
qwen2-72b: /mnt/petrelfs/jiangshuyang/checkpoints/Qwen2-72B-Instruct-GPTQ-Int4
qwen2.5-0.5b: /mnt/petrelfs/jiangshuyang/checkpoints/Qwen2.5-0.5B-Instruct
qwen2.5-1.5b: /mnt/petrelfs/jiangshuyang/checkpoints/Qwen2.5-1.5B-Instruct
qwen2.5-3b: /mnt/petrelfs/jiangshuyang/checkpoints/Qwen2.5-3B-Instruct/
qwen2.5-3b-base: /mnt/petrelfs/jiangshuyang/checkpoints/Qwen2.5-3B/
qwen2.5-7b: /mnt/petrelfs/jiangshuyang/checkpoints/Qwen2.5-7B-Instruct
qwen2.5-7b-base: /mnt/petrelfs/jiangshuyang/checkpoints/Qwen2.5-7B
qwen2.5-32b: /mnt/petrelfs/jiangshuyang/checkpoints/Qwen2.5-32B-Instruct-GPTQ-Int4/
qwen2.5-72b: /mnt/petrelfs/jiangshuyang/checkpoints/Qwen2.5-72B-Instruct-AWQ
llama3-8b: /mnt/petrelfs/jiangshuyang/checkpoints/Meta-Llama-3-8B-Instruct
llama3-70b: /mnt/petrelfs/jiangshuyang/checkpoints/Meta-Llama-3-70B-Instruct-GPTQ
llama3.2-1b: /mnt/petrelfs/jiangshuyang/checkpoints/Llama-3.2-1B-Instruct
llama3.2-3b: /mnt/petrelfs/jiangshuyang/checkpoints/Llama-3.2-3B-Instruct
llama3.2-3b-base: /mnt/petrelfs/jiangshuyang/checkpoints/Llama-3.2-3B
llama3.1-8b: /mnt/petrelfs/jiangshuyang/checkpoints/Meta-Llama-3.1-8B-Instruct
llama3.1-70b: /mnt/petrelfs/jiangshuyang/checkpoints/Meta-Llama-3.1-70B-Instruct-AWQ-INT4
medllama3-8b: /mnt/petrelfs/jiangshuyang/checkpoints/MedLlama-3-8b-v2.0
mmed-llama3: /mnt/petrelfs/jiangshuyang/checkpoints/MMed-Llama-3-8B
mmeds-llama3: /mnt/petrelfs/jiangshuyang/checkpoints/MMedS-Llama3-3-8B
openbiollm: /mnt/petrelfs/jiangshuyang/checkpoints/Llama3-OpenBioLLM-8B/
qwq: /mnt/petrelfs/jiangshuyang/checkpoints/QwQ-32B-Preview/
llama3-med42: /mnt/petrelfs/jiangshuyang/checkpoints/Llama3-Med42-8B
huatuo-o1: /mnt/petrelfs/jiangshuyang/checkpoints/HuatuoGPT-o1-8B
ultramedical-8b: /mnt/petrelfs/jiangshuyang/checkpoints/Llama-3-8B-UltraMedical
ultramedical3.1-8b: /mnt/petrelfs/jiangshuyang/checkpoints/Llama-3.1-8B-UltraMedical
phi3.5: /mnt/petrelfs/jiangshuyang/checkpoints/Phi-3.5-mini-instruct
r1distill-qwen-32b: /mnt/petrelfs/jiangshuyang/checkpoints/DeepSeek-R1-Distill-Qwen-32B
r1distill-qwen-1.5b: /mnt/petrelfs/jiangshuyang/checkpoints/DeepSeek-R1-Distill-Qwen-1.5B
r1distill-qwen-7b: /mnt/petrelfs/jiangshuyang/checkpoints/DeepSeek-R1-Distill-Qwen-7B
gemma3-4b-base: /mnt/petrelfs/jiangshuyang/checkpoints/gemma-3-4b-pt




  


